module.exports = {
  "iConnectionFailed": -1,
  "sConnectionFailed": "The TPC JSON connection failed",
  "iInvalidJSON": -2,
  "sInvalidJSON": "The remote end sent invalid JSON data",
  "iInvalidJSONRPC": -3,
  "sUnexpectedJSONRPCInitialize": "A JSON RPC initialize message is not expected at this time",
  "sUnexpectedJSONRPCVersionRequest": "A JSON RPC version request message is not expected at this time",
  "sUnexpectedJSONRPCVersionAccept": "A JSON RPC version accept message is not expected at this time",
  "sUnexpectedJSONRPCVersionReject": "A JSON RPC version reject message is not expected at this time",
  "sInvalidJSONRPCInitialize": "The JSON RPC initialize message is invalid",
  "sInvalidJSONRPCVersionReject": "The JSON RPC version reject message is invalid",
  "sInvalidJSONRPCVersionAccept": "The JSON RPC version accept message is invalid",
  "sRejectedJSONRPCVersion": "The requested JSON RPC version is rejected",
  "iProcedureNotFound": -4,
  "sProcedureNotFound": "The requested procedure is not found",
  "iInvalidId": -5,
  "sInvalidId": "The result id is invalid",
  "iProcedureFailed": -6,
  "sProcedureFailed": "The procedure call failed because of an unhandled exception",
  "iResultTimeout": -7,
  "sResultTimeout": "The procedure call failed because it timed out",
};